### ISSUE TITLE
Cannot read property 'cssRules' of undefined @styled-components branch

### ISSUE THREAD

**Issue by Jimeno0** [ads1018/next-apollo-example#5]
Hi mate!
As I said in medium awesome work here! 😃 

Im working in a project based on the styled-components branch and I found out that if you don't import any `styled-components` component the server throws a 500 internal-server error and checking the console:

```bash 
TypeError: Cannot read property 'cssRules' of undefined
    at StyleSheet.rules (/Users/CharlieMac/repos/next-apollo/node_modules/styled-components/lib/vendor/glamor/sheet.js:200:26)
    at StyleSheet.rules (/Users/CharlieMac/repos/next-apollo/node_modules/styled-components/lib/models/StyleSheet.js:54:36)
    at Function._callee$ (/Users/CharlieMac/repos/next-apollo/.next/dist/pages/_document.js:116:123)
    at tryCatch (/Users/CharlieMac/repos/next-apollo/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/CharlieMac/repos/next-apollo/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/CharlieMac/repos/next-apollo/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/CharlieMac/repos/next-apollo/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/CharlieMac/repos/next-apollo/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at F (/Users/CharlieMac/repos/next-apollo/node_modules/core-js/library/modules/_export.js:35:28)
    at Function.<anonymous> (/Users/CharlieMac/repos/next-apollo/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
TypeError: Cannot read property 'cssRules' of undefined
    at StyleSheet.rules (/Users/CharlieMac/repos/next-apollo/node_modules/styled-components/lib/vendor/glamor/sheet.js:200:26)
    at StyleSheet.rules (/Users/CharlieMac/repos/next-apollo/node_modules/styled-components/lib/models/StyleSheet.js:54:36)
    at Function._callee$ (/Users/CharlieMac/repos/next-apollo/.next/dist/pages/_document.js:116:123)
    at tryCatch (/Users/CharlieMac/repos/next-apollo/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/CharlieMac/repos/next-apollo/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/CharlieMac/repos/next-apollo/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/CharlieMac/repos/next-apollo/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/CharlieMac/repos/next-apollo/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at F (/Users/CharlieMac/repos/next-apollo/node_modules/core-js/library/modules/_export.js:35:28)
    at Function.<anonymous> (/Users/CharlieMac/repos/next-apollo/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
TypeError: Cannot read property 'cssRules' of undefined
    at StyleSheet.rules (/Users/CharlieMac/repos/next-apollo/node_modules/styled-components/lib/vendor/glamor/sheet.js:200:26)
    at StyleSheet.rules (/Users/CharlieMac/repos/next-apollo/node_modules/styled-components/lib/models/StyleSheet.js:54:36)
    at Function._callee$ (/Users/CharlieMac/repos/next-apollo/.next/dist/pages/_document.js:116:123)
    at tryCatch (/Users/CharlieMac/repos/next-apollo/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/CharlieMac/repos/next-apollo/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/CharlieMac/repos/next-apollo/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/CharlieMac/repos/next-apollo/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/CharlieMac/repos/next-apollo/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at F (/Users/CharlieMac/repos/next-apollo/node_modules/core-js/library/modules/_export.js:35:28)
    at Function.<anonymous> (/Users/CharlieMac/repos/next-apollo/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)

```
Currently it doesn't bothers me since I change the style defined in `lib/layout.js` to `styled-components` but I thought that It worth to notice that

Hope It helps! 🍻

**Comment by ads1018** [comment]
Hey man! Thanks for pointing this out. I'm going to look into it. 🍻

**Comment by ads1018** [comment]
Updated to the latest version of styled-components.
